from sqlmodel import Session, select
from database.datatables import Student, InfoFellow, FellowArea, FellowRank


def seed_students(session: Session):
    # Check if there are any students in the database
    existing = session.exec(select(Student)).first()

    if existing:
        return

    students = [
        Student(
            firstName="Lucia",
            lastName="Amaya Caceda",
            middleName="de Fatima",
            studentCode="L4F1C",
            career="Ingeniería",
            urlProfile="t1051300621@unitru.edu.pe"
        ),
        Student(
            firstName="Silvana",
            lastName="Pereda Llave",
            middleName="Valeria",
            studentCode="S23P12",
            career="Ingeniería",
            urlProfile="speredal@unitru.edu.pe"
        ),
        Student(
            firstName="Marina",
            lastName="Gonzales Torres",
            middleName="Lizeth",
            studentCode="M12G21",
            career="Ingeniería",
            urlProfile="t1510600121@unitru.edu.pe"
        ),
        Student(
            firstName="Diego",
            lastName="Rodriguez Sabana",
            middleName="Jesus",
            studentCode="D10R20",
            career="Ingeniería",
            urlProfile="t1010100421@unitru.edu.pe"
        ),
        Student(
            firstName="Angel",
            lastName="Iparraguirre Aguilar",
            middleName="",
            studentCode="A9A",
            career="Ingeniería",
            urlProfile="t1024000721@unitru.edu.pe"
        ),
        Student(
            firstName="María",
            lastName="Herrera Cerquín",
            middleName="Fernanda de la Caridad",
            studentCode="M6D12C8C",
            career="Ingeniería",
            urlProfile="mfherrerace@unitru.edu.pe"
        ),
        Student(
            firstName="Christian",
            lastName="Morales Esquivel",
            middleName="Anthony",
            studentCode="C1M5",
            career="Ingeniería",
            urlProfile="chmoralese@unitru.edu.pe"
        ),
        Student(
            firstName="Sebastian",
            lastName="Facundo Reyes",
            middleName="Emanuel",
            studentCode="S5F19",
            career="Ingeniería",
            urlProfile="t1512400421@unitru.edu.pe"
        ),
        Student(
            firstName="Zulema",
            lastName="Valverde Zavaleta",
            middleName="Adeli",
            studentCode="Z1V27",
            career="Ingeniería",
            urlProfile="t1510100321@unitru.edu.pe"
        ),
        Student(
            firstName="Ivanna",
            lastName="Vela Ocampo",
            middleName="Sofia",
            studentCode="I20V16",
            career="Ingeniería",
            urlProfile="t510100520@unitru.edu.pe"
        ),
        Student(
            firstName="Anderson",
            lastName="Saavedra Nolasco",
            middleName="Alexander",
            studentCode="A1S14",
            career="Ingeniería",
            urlProfile="aasaavedrano@unitru.edu.pe"
        ),
        Student(
            firstName="Cristhian",
            lastName="Sánchez Obeso",
            middleName="Luis David",
            studentCode="C12D20O",
            career="Ingeniería",
            urlProfile="clsanchezo@unitru.edu.pe"
        ),
        Student(
            firstName="Eleanor",
            lastName="Roca Mendoza",
            middleName="Marycielo",
            studentCode="E13R13",
            career="Ingeniería",
            urlProfile="emrocam@unitru.edu.pe"
        ),
        Student(
            firstName="Emilly",
            lastName="Zavaleta Chigne",
            middleName="Nicoll",
            studentCode="F14Z3",
            career="Ingeniería",
            urlProfile="enzavaletac@unitru.edu.pe"
        ),
        Student(
            firstName="Joaquin",
            lastName="Bocanegra Peláez",
            middleName="Adriano",
            studentCode="J1B17",
            career="Ingeniería",
            urlProfile="jabocanegrap@unitru.edu.pe"
        ),
        Student(
            firstName="Luis",
            lastName="Montoya Aguirre",
            middleName="Enrique",
            studentCode="L5M1",
            career="Ingeniería",
            urlProfile="lemontoyaa@unitru.edu.pe"
        ),
        Student(
            firstName="Valeria",
            lastName="Valderrama Muñoz",
            middleName="Angelie",
            studentCode="V1V13",
            career="Ingeniería",
            urlProfile="vavalderramam@unitru.edu.pe"
        ),
        Student(
            firstName="Ana",
            lastName="Segura Aredo",
            middleName="Nicoll",
            studentCode="A14S1",
            career="Ingeniería",
            urlProfile="anseguraa@unitru.edu.pe"
        ),
        Student(
            firstName="Andrweeu",
            lastName="Urtecho Avila",
            middleName="Daniel",
            studentCode="A4U1",
            career="Ingeniería",
            urlProfile="aurtechoa@unitru.edu.pe"
        ),
        Student(
            firstName="Corina",
            lastName="Sanchez Delgado",
            middleName="Marilu",
            studentCode="C13S4",
            career="Ingeniería",
            urlProfile="csanchezd@unitru.edu.pe"
        ),
        Student(
            firstName="José",
            lastName="Avila Santillan",
            middleName="Daniel",
            studentCode="J4A20",
            career="Ingeniería",
            urlProfile="jdavilas@unitru.edu.pe"
        ),
        Student(
            firstName="Lisseth",
            lastName="Chávez Rosales",
            middleName="Adelaida",
            studentCode="L1C19",
            career="Ingeniería",
            urlProfile="lichavezr@unitru.edu.pe"
        ),
        Student(
            firstName="Mariann",
            lastName="Fernández Leyva",
            middleName="Estefany",
            studentCode="M5F12",
            career="Ingeniería",
            urlProfile="t1050102021@unitru.edu.pe"
        ),
        Student(
            firstName="Michael",
            lastName="García García",
            middleName="Junior",
            studentCode="M10G7",
            career="Ingeniería",
            urlProfile="t1051300421@unitru.edu.pe"
        ),
        Student(
            firstName="Nashaly",
            lastName="Alama Terrones",
            middleName="Nicolle",
            studentCode="N14A21",
            career="Ingeniería",
            urlProfile="nalama@unitru.edu.pe"
        ),
        Student(
            firstName="Renzo",
            lastName="Carrasco Lalangui",
            middleName="Georkael",
            studentCode="R7C12",
            career="Ingeniería",
            urlProfile="rgcarrascol@unitru.edu.pe"
        ),
        Student(
            firstName="Alisson",
            lastName="Pretell Canchas",
            middleName="Milagros",
            studentCode="A13P3",
            career="Ingeniería",
            urlProfile="t050601920@unitru.edu.pe"
        ),
        Student(
            firstName="Dulce",
            lastName="Chavez Padilla",
            middleName="Geraldine",
            studentCode="D7C17",
            career="Ingeniería",
            urlProfile="t1051302521@unitru.edu.pe"
        ),
        Student(
            firstName="Elber",
            lastName="Pichén Zavaleta",
            middleName="Isaí",
            studentCode="E9P2",
            career="Ingeniería",
            urlProfile="t1024000121@unitru.edu.pe"
        ),
        Student(
            firstName="Cristhian",
            lastName="Campos Castro",
            middleName="Imanol",
            studentCode="C9C3",
            career="Ingeniería",
            urlProfile="cicamposc@unitru.edu.pe"


        ),
        Student(
            firstName="Sadhu",
            lastName="Rojas García",
            middleName="",
            studentCode="S19G",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Paúl",
            lastName="Lazaro Solano",
            middleName="Jamir",
            studentCode="P10L20",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Mirella",
            lastName="Gamboa Valderrama",
            middleName="Esteffany",
            studentCode="M5G23",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Marco",
            lastName="Toledo Campos",
            middleName="Camilo",
            studentCode="M3T3",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Luis",
            lastName="Morales Lino",
            middleName="Angel",
            studentCode="L1M12",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Renato",
            lastName="Martinez Aguilar",
            middleName="Alexander",
            studentCode="R1M1",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Pablo",
            lastName="Sánchez Cabrera",
            middleName="César",
            studentCode="P3S3",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Jhoanny",
            lastName="Vargas Ramos",
            middleName="Jheimilyn Xiomara",
            studentCode="J10X23R",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Elder",
            lastName="De la Cruz Calderón",
            middleName="Eli",
            studentCode="E5D12C3",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Maria",
            lastName="Huaman Martinez",
            middleName="Celine",
            studentCode="M3H13",
            career=None,
            urlProfile="fotos_firmas/Maria Celine Huaman Martinez.png",
        ),
        Student(
            firstName="Aaron",
            lastName="Arteaga Rodriguez",
            middleName="Kaleb",
            studentCode="A11A19",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Jeoselyn",
            lastName="Espejo Rodríguez",
            middleName="Maribel",
            studentCode="J13E19",
            career=None,
            urlProfile="fotos_firmas/Jeoselyn Maribel Espejo Rodriguez.png",
        ),
        Student(
            firstName="Ruben",
            lastName="Alcantara Toribio",
            middleName="Dario",
            studentCode="R4A21",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Diego",
            lastName="Gutierrez Vasquez",
            middleName="Alonso",
            studentCode="D1G23",
            career=None,
            urlProfile="fotos_firmas/Diego Alonso Gutierrez Vasquez.png",
        ),
        Student(
            firstName="Diego",
            lastName="Mostacero Lecca",
            middleName="Alejandro",
            studentCode="D1M12",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Dalery",
            lastName="Alayo Sifuentes",
            middleName="Nicoll",
            studentCode="D14AS",
            career=None,
            urlProfile="fotos_firmas/Dalery Nicoll Alayo Sifuentes.png",
        ),
        Student(
            firstName="Angela",
            lastName="Loayza Gutierrez",
            middleName="Xiomara",
            studentCode="A25L7",
            career=None,
            urlProfile="fotos_firmas/Angela Xiomara Loayza Gutierrez.png",
        ),
        Student(
            firstName="Abel",
            lastName="Pereda Cabanillas",
            middleName="Maximiliano",
            studentCode="A13P3",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Daniel",
            lastName="Sanchez Cabrera",
            middleName="Angel",
            studentCode="D1S3",
            career=None,
            urlProfile="fotos_firmas/Daniel Angel Sanchez Cabrera.png",
        ),
        Student(
            firstName="Sebastian",
            lastName="Vásquez Estrada",
            middleName="Javier",
            studentCode="S10V5",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Rodrigo",
            lastName="Quispe Cortijo",
            middleName="Alexander",
            studentCode="R1Q3",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Ariana",
            lastName="Morales Ipanaqué",
            middleName="",
            studentCode="A13I",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Ghenary",
            lastName="Esquivel Davila",
            middleName="Tais",
            studentCode="G21E4",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Anderson",
            lastName="Otiniano Morales",
            middleName="Abat",
            studentCode="A1O13",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Stefany",
            lastName="Gutierrez Vega",
            middleName="Isabel",
            studentCode="S9G23",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Maria",
            lastName="Cárdenas Hidalgo",
            middleName="Fernanda",
            studentCode="M6C8",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Yojhania",
            lastName="Gonzales Contreras",
            middleName="Taitt",
            studentCode="Y21G3",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Jordyna",
            lastName="Robles Solorzano",
            middleName="Del Carmen",
            studentCode="J4C19S",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Jakori",
            lastName="Hoyos Terrones",
            middleName="Nayeli",
            studentCode="J14H21",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Emelyn",
            lastName="Aguirre Valverde",
            middleName="Yasmin",
            studentCode="E26A23",
            career=None,
            urlProfile=None,
        ),
        Student(
            firstName="Cielo",
            lastName="Abanto Rojas",
            middleName="Valentina",
            studentCode="C23A19",
            career=None,
            urlProfile=None,
        ),
        # 30 LAST ESTUDENTS
        Student(
            firstName="Dalia Irina",
            middleName="Garcia",
            lastName="De la Cruz",
            studentCode="D9G4L3",
            career="Ingeniería",
            urlProfile="https://example.com/daliagarcia",
        ),
        Student(
            firstName="Diego Andree",
            middleName="Andree",
            lastName="Garro Taboada",
            studentCode="D1G21",
            career="Ingeniería",
            urlProfile="https://example.com/diegogarro",
        ),
        Student(
            firstName="Fabiana",
            middleName="Belen",
            lastName="Sosa Parra",
            studentCode="F2S17",
            career="Ingeniería",
            urlProfile="https://example.com/fabianasosa",
        ),
        Student(
            firstName="Nory Ann",
            middleName="Marie",
            lastName="Touzet Meneses",
            studentCode="N1M21M",
            career="Ingeniería",
            urlProfile="https://example.com/norytouzet",
        ),
        Student(
            firstName="Priscila",
            middleName="Crystal",
            lastName="Villegas Dominguez",
            studentCode="P3V4",
            career="Ingeniería",
            urlProfile="https://example.com/priscilavillegas",
        ),
        Student(
            firstName="Yamelyn",
            middleName="Leslie",
            lastName="Rios Tandaypan",
            studentCode="Y12R21",
            career="Ingeniería",
            urlProfile="https://example.com/yamelynrios",
        ),
        Student(
            firstName="Christian",
            middleName="Rodrigo",
            lastName="Valverde Caspito",
            studentCode="C19V3",
            career="Ingeniería",
            urlProfile="https://example.com/christianvalverde",
        ),
        Student(
            firstName="Eddie",
            middleName="Alessandro",
            lastName="Jiménez Vilchez",
            studentCode="E1J23",
            career="Ingeniería",
            urlProfile="https://example.com/eddiejimenez",
        ),
        Student(
            firstName="Fabián",
            middleName="Nicolas",
            lastName="Paredes Calderón",
            studentCode="F14P3",
            career="Ingeniería",
            urlProfile="https://example.com/fabianparedes",
        ),
        Student(
            firstName="Kiara",
            middleName="Marife",
            lastName="Rodriguez Sifuentes",
            studentCode="K13R20",
            career="Ingeniería",
            urlProfile="https://example.com/kiararodriguez",
        ),
        Student(
            firstName="Luis",
            middleName="Angel",
            lastName="Laureano Escobedo",
            studentCode="L1L5",
            career="Ingeniería",
            urlProfile="https://example.com/luislaureano",
        ),
        Student(
            firstName="Grecia",
            middleName="Alexandra",
            lastName="Paredes Cachique",
            studentCode="G1P3",
            career="Ingeniería",
            urlProfile="https://example.com/greciaparedes",
        ),
        Student(
            firstName="Maria",
            middleName="Fernanda",
            lastName="Pretell Leon",
            studentCode="M6P12",
            career="Ingeniería",
            urlProfile="https://example.com/mariapretell",
        ),
        Student(
            firstName="Mixie",
            middleName="Arleni",
            lastName="Gil Zapata",
            studentCode="M1G27",
            career="Ingeniería",
            urlProfile="https://example.com/mixiegil",
        ),
        Student(
            firstName="Nestor Rafael",
            middleName="Plasencia",
            lastName="De la Cruz",
            studentCode="N19P4L3",
            career="Ingeniería",
            urlProfile="https://example.com/nestorplasencia",
        ),
        Student(
            firstName="Tatiana",
            middleName="Yuleisy",
            lastName="Aliaga Pretell",
            studentCode="T26A17",
            career="Ingeniería",
            urlProfile="https://example.com/tatianaaliaga",
        ),
        Student(
            firstName="Kevin",
            middleName="Gamaliel",
            lastName="Rodríguez Alfaro",
            studentCode="K7R1",
            career="Ingeniería",
            urlProfile="https://example.com/kevinrodriguez",
        ),
        Student(
            firstName="Fernanda ",
            middleName="Milagros",
            lastName="Rojas Rodriguez",
            studentCode="F13R19",
            career="Ingeniería",
            urlProfile="https://example.com/fernandarojas",
        ),
        Student(
            firstName="Adriana",
            middleName="Gabriela",
            lastName="Castillo Ochoa",
            studentCode="A7C16",
            career="Ingeniería",
            urlProfile="https://example.com/adrianacastillo",
        ),
        Student(
            firstName="Angelo",
            middleName="Salvattore",
            lastName="Chavarry Bustamante",
            studentCode="A20C2",
            career="Ingeniería",
            urlProfile="https://example.com/angelochavarry",
        ),
        Student(
            firstName="Cesar",
            middleName="Junior",
            lastName="Quito Cruz",
            studentCode="C10Q3",
            career="Ingeniería",
            urlProfile="https://example.com/cesarquito",
        ),
        Student(
            firstName="Juan",
            middleName="José",
            lastName="Chávez Tenorio",
            studentCode="J10C21",
            career="Ingeniería",
            urlProfile="https://example.com/juanchavez",
        ),
        Student(
            firstName="Lorena",
            middleName="Midalís",
            lastName="Primo Bueno",
            studentCode="L13P2",
            career="Ingeniería",
            urlProfile="https://example.com/lorenaprimo",
        ),
        Student(
            firstName="Malena",
            middleName="Shecid",
            lastName="Huamán Arana",
            studentCode="M20H1",
            career="Ingeniería",
            urlProfile="https://example.com/malenahuaman",
        ),
        Student(
            firstName="Melissa",
            middleName="del Rosario",
            lastName="Muñoz Uriarte",
            studentCode="M4R13U",
            career="Ingeniería",
            urlProfile="https://example.com/melissamunoz",
        ),
        Student(
            firstName="Milene",
            middleName="Xiomara",
            lastName="Delgado Silva",
            studentCode="M25D20",
            career="Ingeniería",
            urlProfile="https://example.com/milenedelgado",
        ),
        Student(
            firstName="Belinda",
            middleName="Maricielo",
            lastName="Arroyo Esquivel",
            studentCode="B13A5",
            career="Ingeniería",
            urlProfile="https://example.com/belindaarroyo",
        ),
        Student(
            firstName="Diego Jesús",
            middleName="Ullilén Chávez",
            lastName="Chávez",
            studentCode="D10U3",
            career="Ingeniería",
            urlProfile="https://example.com/diegoullilen",
        ),
        Student(
            firstName="Luis",
            middleName="Angel",
            lastName="Lecca Cortez",
            studentCode="L1L3",
            career="Ingeniería",
            urlProfile="https://example.com/luislecca",
        ),
        Student(
            firstName="Angie",
            middleName="Tatiana",
            lastName="Recuenco Tapia",
            studentCode="A21R21",
            career="Ingeniería",
            urlProfile="https://example.com/angierecuenco",
        ),
    ]
    session.add_all(students)
    session.commit()
    print("✅ Seeder ejecutado correctamente")
